// flow-typed signature: f7ab55d516af01a0df819013ed1d5832
// flow-typed version: <<STUB>>/buffer_v5.2.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'buffer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'buffer' {
  declare module.exports: any;
}
