// flow-typed signature: a46cf3eef766047653f6c3d02b6fac5d
// flow-typed version: <<STUB>>/bugsnag-react-native_v2.10.2/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bugsnag-react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bugsnag-react-native' {
  declare module.exports: any;
}
