// flow-typed signature: 8549f53426c6ad544a2c3301fc6855f6
// flow-typed version: <<STUB>>/react-native-vector-icons_v5.0.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-vector-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-vector-icons' {
  declare module.exports: any;
}
