// flow-typed signature: 9dd1a05bf3c45ee9fdf1ce1ebb91582a
// flow-typed version: <<STUB>>/react-native-popover-view_v1.0.4/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-popover-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-popover-view' {
  declare module.exports: any;
}
