// flow-typed signature: 4f3e9b6518cf82dec7204f66f0b3cfc1
// flow-typed version: <<STUB>>/react-native-onesignal_v3.1.4/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-onesignal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-onesignal' {
  declare module.exports: any;
}
